name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./BACKEND
          push: false
          tags: breast-cancer-backend:latest
          outputs: type=docker,dest=/tmp/backend-image.tar

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app
          push: false
          tags: breast-cancer-frontend:latest
          outputs: type=docker,dest=/tmp/frontend-image.tar

      - name: Load images
        run: |
          docker load --input /tmp/backend-image.tar
          docker load --input /tmp/frontend-image.tar

      - name: Verify images
        run: |
          docker images
          echo "✅ CI/CD Pipeline completed successfully!"
